### ISSUE TITLE
data_package_download and long file paths

### ISSUE THREAD

**Issue by atn38** [IMCR-Hackathon/ggplotgui#41] opened 2019-06-21 20:56 UTC
`data_package_download` gives this warning when used with this DOI `doi:10.6073/pasta/ef77fb0348fc0d31e7d3875c947aaa4e`

```
Warning messages:
1: In file.copy(from = pkg_dir_name, to = parent_dir, recursive = TRUE) :
  over-long path length
```

End results is only data file gets copied over to directory specified in `download.dir` argument while metadata files -- whose names are longer -- do not make it. This is probably a Window-specific issue (260 characters limit to file paths). 

If I use `metajam::download_d1_pkg` directly, both data and metadata are there. The file paths generally are shorter with this option.

Using `data_package_download`, data file path for above DOI works out to be: `download.dir/https_pasta.lternet.edu_package_metadata_eml_knb-lter-ntl_364_1/https_pasta.lternet.edu_package_metadata_eml_knb-lter-ntl_364_1__LakeMendota_SpatialSurfaceChemistry__csv/LakeMendota_SpatialSurfaceChemistry.csv`

Using `metajam::download_d1_pkg`, data file path is shorter: `download.dir/https_pasta.lternet.edu_package_metadata_eml_knb-lter-ntl_364_1__LakeMendota_SpatialSurfaceChemistry__csv/LakeMendota_SpatialSurfaceChemistry.csv`

**Comment by clnsmth** [comment] 2019-06-23 03:50
This issue is a duplicate of #40

**Closed by clnsmth** 2019-06-23 03:50 UTC
Labels: duplicate
